/** to void magic strings **/
export const envNamesConf = {
  SERVER_PORT: 'SERVER_PORT',
  DATABASE_TYPE: 'DATABASE_TYPE',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRE: 'JWT_ACCESS_TOKEN_EXPIRE',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRE: 'JWT_REFRESH_TOKEN_EXPIRE',
  JWT_BLOCK_ALL: 'JWT_BLOCK_ALL',
  DEFAULT_ADMIN_EMAIL: 'DEFAULT_ADMIN_EMAIL',
  DEFAULT_ADMIN_PASSWORD: 'DEFAULT_ADMIN_PASSWORD',
  DEFAULT_ADMIN_ROLE: 'DEFAULT_ADMIN_ROLE',
};
